### ISSUE TITLE
Organization / project logo?

### ISSUE THREAD

**Issue by ian-h-chamberlain** [rust3ds/.github#2]
Hey all @rust3ds/active, I thought it might be nice for the project to have a logo to go along with the new README and the planned release. I whipped this one up quickly (but I'm by no means a designer/artist), let me know what you think.

Edit: scaled to a couple common sized I found on GitHub, then full size. It doesn't scale quite as well as I'd hoped, maybe I'll see if I can improve that at all:

<details>
<summary>uncropped (slight margin on edges)</summary>

<img src="https://user-images.githubusercontent.com/11131775/225770301-d4303173-a63c-4903-80a1-45576727aabd.png" width="20"/> <img src="https://user-images.githubusercontent.com/11131775/225770301-d4303173-a63c-4903-80a1-45576727aabd.png" width="44"/> <img src="https://user-images.githubusercontent.com/11131775/225770301-d4303173-a63c-4903-80a1-45576727aabd.png" width="100"/>

![rust-3ds](https://user-images.githubusercontent.com/11131775/225770301-d4303173-a63c-4903-80a1-45576727aabd.png)
</details>

<details>
<summary>cropped down to content (no margin)</summary>

<img src="https://user-images.githubusercontent.com/11131775/225796839-db1541f4-eb69-4d23-9ad1-a6425faf10aa.png" width="20"/> <img src="https://user-images.githubusercontent.com/11131775/225796839-db1541f4-eb69-4d23-9ad1-a6425faf10aa.png" width="44"/> <img src="https://user-images.githubusercontent.com/11131775/225796839-db1541f4-eb69-4d23-9ad1-a6425faf10aa.png" width="100"/> 
![225770301-d4303173-a63c-4903-80a1-45576727aabd](https://user-images.githubusercontent.com/11131775/225796839-db1541f4-eb69-4d23-9ad1-a6425faf10aa.png)

</details>

I made it using all freely licensed images:
- https://freesvg.org/handheld-3d-game-system (public domain)
- https://rustacean.net/ (public domain)
- https://carbon.now.sh (free use according to their website / github)

Thoughts? Any changes to make? @Meziu will probably have to set the icon as an organization owner, I would guess.

**Comment by Meziu** [comment]
Haha, nice! This is miles better than the static GitHub icon, affirmative from me 👍

**Comment by AzureMarker** [comment]
Wow, better than what I could "whip up"!

**Comment by Meziu** [comment]
Well, after adding it, I must say it looks great! This will stay for sure. We could add it around as default icon for some other things (maybe default logo of cargo-3ds executables?)

**Comment by ian-h-chamberlain** [comment]
> Well, after adding it, I must say it looks great! This will stay for sure. We could add it around as default icon for some other things (maybe default logo of cargo-3ds executables?)

I was thinking about other use cases, I wouldn't be opposed to making it the default logo instead of `$DEVKITPRO/libctru/default_icon.png`, but we'd have to figure out how to ship the image with `cargo-3ds` itself (probably doable, but perhaps slightly annoying with an `include_bytes!` and writing a file to disk on each build, or something). Also we'd probably want to shrink it down to match the 48x48 size of the default one.

Otherwise there aren't too many cases I can think of, since `cargo-3ds` isn't shipped like a normal graphical application bundle it doesn't make much sense to try and use it as the icon there. We can see if any other use cases come up that make sense though.

----

@Meziu thanks for setting the new image! It looks like it got cropped a little by GitHub (you can see [here](https://avatars.githubusercontent.com/u/20054503?s=400&v=40)) which I realized is probably because I forgot to make sure it's square, can you try this version to see if that helps?

<details>
<summary>cropped to square, with small margin</summary>

![rust-3ds-cropped-square](https://user-images.githubusercontent.com/11131775/225929072-2fa1741c-93ae-4b47-9bdf-af70f3d59910.png)

</details>

**Comment by Meziu** [comment]
I've fixed the icon cropping, thanks.

**Comment by ian-h-chamberlain** [comment]
Cool, I think we are done with this for now then! Thanks
